# Default values for kube-prometheus-stack.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
kube-prometheus-stack:
  ## Using default values from https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml
  ##
  grafana:
    adminPassword: <path:devsecops/data/apps/prometheus-stack/int/grafana#adminPassword>

domain: "int.demo.catena-x.net"
cluster: "hotel-budapest"
