# TODO 08.04.2022 CARSLEN: bearerToken needs to be evaluated via SP login from kubeconfig
apiVersion: v1
kind: Secret
metadata:
  annotations:
    avp.kubernetes.io/path: "devsecops/data/clusters/vault/k8s"
  labels:
    argocd.argoproj.io/secret-type: cluster
  name: vault-cluster-secret
type: Opaque
stringData:
  name: <name>
  server: <server>
  config: |
    {
      "bearerToken": "<bearerToken>",
      "tlsClientConfig": {
        "insecure": false,
        "caData": "<caData>"
      }
    }
