apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kube-prometheus-stack-applicationset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: core
            cluster-name: in-cluster
            targetRevision: 35.5.1
#          - cluster: dev
#            cluster-name: dev
#            targetRevision: 35.5.0
#          - cluster: hotel-budapest
#            cluster-name: hotel-budapest
#            targetRevision: 35.5.0
# TODO 01.06.2022 CARSLEN: shall kube-prometheus-stack be installed to vault?
#          - cluster: vault
#            cluster-name: vault-cluster
#            targetRevision: 35.5.0

  template:
    metadata:
      name: '{{ cluster }}-kube-prometheus-stack'
      labels:
        app: kube-prometheus-stack
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        helm:
          skipCrds: true
        chart: kube-prometheus-stack
        repoURL: https://prometheus-community.github.io/helm-charts
        targetRevision: '{{ targetRevision }}'
      destination:
        name: '{{ cluster-name }}'
        namespace: kube-prometheus-stack
        server: ''
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m

