apiVersion: v1
kind: Secret
metadata:
  annotations:
    avp.kubernetes.io/path: "devsecops/data/azure/demo.catena-x.net/azure-vault-secret"
  name: azure-vault-secret
  namespace: {{ .Release.Namespace}}
type: Opaque
stringData:
  client-secret: <client-secret>
