apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{.Values.vault.name}}
  namespace: {{.Values.vault.namespace}}
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: vault
    meta.helm.sh/release-namespace: argocd
spec:
  project: {{.Values.vault.project}}
  source:
    repoURL: {{.Values.vault.source.repourl}}
    targetRevision: {{.Values.vault.source.targetrevision}}
    helm:
      parameters:
        - name: server.ha.enabled
          value: 'true'
        - name: server.ha.raft.enabled
          value: 'true'
        - name: server.ha.raft.config
          value: |
            ui = true
            listener "tcp" {
              tls_disable = 1
              address = "[::]:8200"
              cluster_address = "[::]:8201"
            }
            storage "raft" {
              path = "/vault/data"
            }
            service_registration "kubernetes" {}
            disable_mlock = true
            seal "azurekeyvault" {
              tenant_id = "{{.Values.vault.seal.tenantid}}"
              client_id = "{{.Values.vault.seal.clientid}}"
              client_secret = "{{.Values.vault.seal.clientsecret}}"
              vault_name = "{{.Values.vault.seal.azurevaultname}}"
              key_name = "{{.Values.vault.seal.azurevaultkeyname}}"
              subscription_id = "{{.Values.vault.seal.subscriptionid}}"
            }
        - name: server.ha.config
          value: |
            ui = true
            listener "tcp" {
              tls_disable = 1
              address = "[::]:8200"
              cluster_address = "[::]:8201"
            }
            storage "raft" {
              path = "/vault/data"
            }
            service_registration "kubernetes" {}
            disable_mlock = true
            seal "azurekeyvault" {
              tenant_id = "{{.Values.vault.seal.tenantid}}"
              client_id = "{{.Values.vault.seal.clientid}}"
              client_secret = "{{.Values.vault.seal.clientsecret}}"
              vault_name = "{{.Values.vault.seal.azurevaultname}}"
              key_name = "{{.Values.vault.seal.azurevaultkeyname}}"
              subscription_id = "{{.Values.vault.seal.subscriptionid}}"
            }
    chart: vault
  destination:
    server: {{.Values.vault.destination.server}}
    namespace: {{.Values.vault.destination.namespace}}
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
