apiVersion: v1
kind: Namespace
metadata:
  name: product-innovation-radar
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project-innovation-radar
  namespace: argocd
spec:
  description: Project for team Innovation Radar
  sourceRepos:
    - '*'
  destinations:
    - namespace: product-innovation-radar
      server: https://kubernetes.default.svc
  # Allow all namespaced-scoped resources to be created, except for ResourceQuota, LimitRange, NetworkPolicy
  namespaceResourceBlacklist:
    - group: ''
      kind: ResourceQuota
    - group: ''
      kind: LimitRange
    - group: ''
      kind: NetworkPolicy
  roles:
    - name: team-admin
      description: All access to applications inside project-innovation-radar. Read only on project itself
      policies:
        - p, proj:project-innovation-radar:team-admin, applications, *, project-innovation-radar/*, allow
      groups:
        - catenax-ng:product-innovation-radar
