# Argo CD -> User management -> Dex: https://argo-cd.readthedocs.io/en/stable/operator-manual/user-management/#dex
# Create OAuth App Client ID/Secret (e.g. https://github.com/organizations/catenax-ng/settings/applications)
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
#  namespace: argocd
data:
  dex.config: |
    connectors:
      - type: github
        id: github
        name: GitHub
        config:
          clientID: $dex.github.clientId
          clientSecret: $dex.github.clientSecret
          orgs:
          - name: catenax-ng
  url: #{{ required "A valid value is required! (.Values.github.argoUrl)" .Values.github.argoUrl }}
