apiVersion: v1
kind: ConfigMap
metadata:
  name: cmp-plugin
data:
  avp-kustomize.yaml: |
    ---
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: argocd-vault-plugin-kustomize
    spec:
      allowConcurrency: true
      discover:
        find:
          command: [sh, -c, "find . -name kustomization.yaml"] 
      generate:
        command: [sh, -c, "kustomize build . | argocd-vault-plugin generate - -s vault-secret"]
      lockRepo: false
  avp-helm-kustomize.yaml: |
    ---
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: argocd-vault-plugin-kustomize-helm-args
    spec:
      allowConcurrency: true
      discover:
        find:
          command:
            - sh
            - "-c"
            - |
              if [ -n "$(find . -name 'values.yaml' | head -1)" ] &&
                 [ -n "$(find . -name 'Chart.yaml' | head -1)" ] && 
                 [ -n "$(find . -name 'kustomization.yaml' | head -1)" ] &&
                 [ -n "${ARGOCD_ENV_helm_args}" ]; then
                  echo "Hit!"
              fi
      init:
        command: [sh, -c, "helm dependency update"]
      generate:
        command:
          - sh
          - "-c"
          - >-
            helm template $ARGOCD_APP_NAME --include-crds -n $ARGOCD_APP_NAMESPACE ${ARGOCD_ENV_helm_args} . > manifest.yaml && 
            kustomize build | 
            argocd-vault-plugin generate - -s vault-secret
      lockRepo: false
  avp-helm-args.yaml: |
    ---
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: argocd-vault-plugin-helm-args
    spec:
      allowConcurrency: true
      discover:
        find:
          command:
            - sh
            - "-c"
            - >-
              if [ -n "$(find . -name 'values.yaml' | head -1)" ] &&
                 [ -z "$(find . -name 'kustomization.yaml')" ] &&
                 [ -n "$(find . -name 'Chart.yaml' | head -1)" ] &&
                 [ -n "${ARGOCD_ENV_helm_args}" ]; then
                  echo "Hit!"
              fi
      init:
        command: [sh, -c, "helm dependency update"]
      generate:
        command:
          - bash
          - "-c"
          - >-
            helm template $ARGOCD_APP_NAME --include-crds -n $ARGOCD_APP_NAMESPACE $ARGOCD_ENV_helm_args . |
            argocd-vault-plugin generate - -s vault-secret
      lockRepo: false
  avp-helm-values.yaml: |
    ---
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: argocd-vault-plugin-helm
    spec:
      allowConcurrency: true
      discover:
        find:
          command:
            - sh
            - "-c"
            - >-
              if [ -n "$(find . -name 'values.yaml' | head -1)" ] &&
                 [ -n "$(find . -name 'Chart.yaml' | head -1)" ] &&
                 [ -n "$(find . -name '*.yaml' | xargs -I {} grep '<path\|avp\.kubernetes\.io' {})" ] &&
                 [ -z "$(find . -name 'kustomization.yaml')" ] &&
                 [ -z "${ARGOCD_ENV_helm_args}" ]; 
              then
                echo "Hit!"
              fi
      init:
        command: [sh, -c, "helm dependency update"]  
      generate:
        command:
          - bash
          - "-c"
          - >-
            helm template $ARGOCD_APP_NAME -n $ARGOCD_APP_NAMESPACE -f <(echo "$ARGOCD_ENV_HELM_VALUES") . |
            argocd-vault-plugin generate - -s vault-secret
      lockRepo: false
  avp.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: argocd-vault-plugin
    spec:
      allowConcurrency: true
      discover:
        find:
          command:
            - sh
            - "-c"
            - >-
              if [ -z "$(find . -name 'Chart.yaml')" ] &&
                 [ -z "$(find . -name 'kustomization.yaml')" ] &&
                 [ -n "$(find . -name '*.yaml')" ] &&
                 [ -n "$(find . -name '*.yaml' | xargs -I {} grep '<path\|avp\.kubernetes\.io' {})" ];
              then
                 echo "Hit!"
              fi
      generate:
        command:
          - sh
          - "-c"
          - "argocd-vault-plugin generate . -s vault-secret"
      lockRepo: false
