apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: appbundle-kube-prom-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    environment: app-of-apps
spec:
  project: default
  source:
    repoURL: 'https://github.com/catenax-ng/k8s-cluster-stack'
    path: environments/core/applicationsets/kube-prometheus-stack
    targetRevision: 'feature/A1ODT-329_kube-prometheus-stack'
  destination:
    namespace: kube-prometheus-stack
    name: in-cluster
    server: ''
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true