apiVersion: v1
kind: Namespace
metadata:
  name: product-managed-identity-wallets
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project-managed-identity-wallets
  namespace: argocd
spec:
  description: Project for product-managed-identity-wallets
  sourceRepos:
    - '*'
  destinations:
    - namespace: product-managed-identity-wallets
      server: https://kubernetes.default.svc
  # Allow all namespaced-scoped resources to be created, except for ResourceQuota, LimitRange, NetworkPolicy.
  namespaceResourceBlacklist:
    - group: ''
      kind: ResourceQuota
    - group: ''
      kind: LimitRange
    - group: ''
      kind: NetworkPolicy
  roles:
    - name: project-read-only
      description: provide read-only access to project
      policies:
        - p, proj:project-managed-identity-wallets:project-read-only, applications, get, project-managed-identity-wallets/*, allow
      groups:
        - catenax-ng:product-managed-identity-wallets
        - catenax-ng:release-management
        - catenax-ng:test-management