apiVersion: v1
kind: Namespace
metadata:
  name: product-bpdm
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project-bpdm
  namespace: argocd
spec:
  description: Project for product-bpdm
  sourceRepos:
    - '*'
  destinations:
    - namespace: product-bpdm
      server: https://kubernetes.default.svc
  # Allow all namespaced-scoped resources to be created, except for ResourceQuota, LimitRange, NetworkPolicy.
  namespaceResourceBlacklist:
    - group: ''
      kind: ResourceQuota
    - group: ''
      kind: LimitRange
    - group: ''
      kind: NetworkPolicy
  roles:
    - name: project-read-only
      description: provide read-only access to project
      policies:
        - p, proj:project-bpdm:project-read-only, applications, get, project-bpdm/*, allow
      groups:
        - catenax-ng:product-bpdm
        - catenax-ng:release-management
        - catenax-ng:test-management