apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: certmanager-applicationset
spec:
  generators:
  - list:
      elements:
#      - cluster: core
#        url: https://kubernetes.default.svc
#        targetRevision: feature/A10DT-419-setup-default-apps
      - cluster: carslen-hotel-budapest
        url: https://carslendemochild-dns-1511068f.hcp.germanywestcentral.azmk8s.io
        targetRevision: feature/A10DT-419-setup-default-apps

  template:
    metadata:
      name: '{{ cluster }}-certmanager'
      labels:
        app: certmanager
    spec:
      project: default
      source:
        chart: certmanager
        helm:
          valueFiles:
            - values-certmanager.yaml
        repoURL: https://github.com/catenax-ng/k8s-cluster-stack
        targetRevision: '{{ targetRevision }}'
        path: apps/certmanager

      destination:
        server: '{{ url }}'
        namespace: cert-manager
      syncPolicy:
        syncOptions:
          - CreateNamespace=true

      ignoreDifferences: # https://github.com/argoproj/argo-cd/issues/4276#issuecomment-908455476
        - group: admissionregistration.k8s.io
          kind: ValidatingWebhookConfiguration
          name: '{{ cluster }}-certmanager-cert-manager-webhook'
          jsonPointers:
            - /webhooks/0/namespaceSelector/matchExpressions/2
