apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: certmanager-applicationset
spec:
  generators:
  - list:
      elements:
#      - cluster: core
#        url: https://kubernetes.default.svc
      - cluster: carslen-hotel-budapest
        url: https://carslendemobudapest-dns-9bd4168d.hcp.germanywestcentral.azmk8s.io

  template:
    metadata:
      name: '{{ cluster }}-certmanager'
      labels:
        app: certmanager
    spec:
      project: default
      source:
        helm:
          valueFiles:
            - values.yaml
        repoURL: https://github.com/catenax-ng/k8s-cluster-stack
        targetRevision: feature/A10DT-419-setup-default-apps
        path: apps/certmanager

      destination:
        server: '{{ url }}'
        namespace: default
