apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

resources:
  - ingress/ingress-argocd.yaml
  - https://raw.githubusercontent.com/argoproj-labs/argocd-image-updater/stable/manifests/install.yaml

patchesStrategicMerge:
  - configmap/argo-cm.yaml
