apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - ../../base

# Configure rbac to grant catenax-ng:ArgoCDAdmins admin rights to argoCD
patchesStrategicMerge:
  - argo-url.yaml