ingress-nginx:
  controller:
    service:
      loadBalancerIP: 20.113.72.134
    ingressClassResource:
      default: true
    watchIngressWithoutClass: true
    config:
      # @url: https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#enable-underscores-in-headers
      enable-underscores-in-headers: "true"
      #extraArgs:
      #default-ssl-certificate: "default/www-tls"  # K8_NAMESPACE/K8_SECRET_NAME @url: https://kubernetes.github.io/ingress-nginx/user-guide/tls/#default-ssl-certificate
    ## Required only if defaultBackend.enabled = false
    ## Must be <namespace>/<service_name>
    ##
    ## DEPRECATED but new extra Argument has been added.
    ## IMPORTANT If <namespace>/<service_name> is not available, ingress controller will crash (all services are out) because it was designed to make your life miserable!
    extraArgs:
      default-backend-service: $(POD_NAMESPACE)/k8s-default-backend

  defaultBackend:
    ## If false, controller.defaultBackendService must be provided
    ##
    enabled: false

landing-page:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    hosts:
      - host: home.devsecops-testing.demo.catena-x.net
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: tls-secret
        hosts:
          - home.devsecops-testing.demo.catena-x.net
  service:
    environment: "devsecops-testing"
