controller:
  service:
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: "/healthz"
  ingressClassResource:
    default: true
  watchIngressWithoutClass: true
  config:
    # @url: https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#enable-underscores-in-headers
    enable-underscores-in-headers: "true"
  extraArgs:
    default-backend-service: $(POD_NAMESPACE)/k8s-landing-page
    default-ssl-certificate: $(POD_NAMESPACE)/tls-secret