apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  annotations:
    avp.kubernetes.io/path: "devsecops/data/clusters/hotel-budapest/github-oauth"
data:
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: argocd-cm
  data:
    dex.config: |
      connectors:
        - type: github
          id: github
          name: GitHub
          config:
            clientID: '<oAuthClientId>'
            clientSecret: '<oAuthClientSecret>'
            orgs:
            - name: catenax-ng
  url: "https://argo.demo.catena-x.net"
