apiVersion: v1
kind: Namespace
metadata:
  name: product-trace-cs-webapp
---
apiVersion: v1
kind: Namespace
metadata:
  name: product-trace-cs-webapp-pen
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project-trace-cs-webapp
  namespace: argocd
spec:
  description: Project for team DataIntegrityDemonstrator
  sourceRepos:
    - '*'
  destinations:
    - namespace: product-trace-cs-webapp
      server: https://kubernetes.default.svc
    - namespace: product-trace-cs-webapp-pen
      server: https://kubernetes.default.svc
  # Allow all namespaced-scoped resources to be created, except for ResourceQuota, LimitRange, NetworkPolicy
  namespaceResourceBlacklist:
    - group: ''
      kind: ResourceQuota
    - group: ''
      kind: LimitRange
    - group: ''
      kind: NetworkPolicy
  roles:
    # A role which provides access to all applications in the project
    - name: team-admin
      description: All access to applications inside project-data-integrity-demonstrator. Read only on project itself
      policies:
        - p, proj:project-trace-cs-webapp:team-admin, applications, *, project-trace-cs-webapp/*, allow
      groups:
        - catenax-ng:product-trace-cs-webapp
