apiVersion: v1
kind: Namespace
metadata:
  name: product-catenax-at-home
---
apiVersion: v1
kind: Namespace
metadata:
  name: product-catenax-at-home-pen
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project-catenax-at-home
  namespace: argocd
spec:
  description: "Project for team Catena-X@Home"
  sourceRepos:
    - '*'
  destinations:
    - namespace: catenax-at-home
      server: https://kubernetes.default.svc
    - namespace: catenax-at-home-pen
      server: https://kubernetes.default.svc
  namespaceResourceBlacklist:
    - group: ''
      kind: ResourceQuota
    - group: ''
      kind: LimitRange
    - group: ''
      kind: NetworkPolicy
  roles:
    # A role which provides access to all applications in the project
    - name: team-admin
      description: All access to applications inside project-edc. Read only on project itself
      policies:
        - p, proj:project-catenax-at-home, applications, *, project-catenax-at-home/*, allow
        - p, proj:project-catenax-at-home:team-admin, exec, create, project-catenax-at-home/*, allow
      groups:
        - catenax-ng:product-catenax-at-home
