apiVersion: v1
kind: Namespace
metadata:
  name: product-iam
---
apiVersion: v1
kind: Namespace
metadata:
  name: product-iam-pen
---
apiVersion: v1
kind: Namespace
metadata:
  name: product-portal
---
apiVersion: v1
kind: Namespace
metadata:
  name: product-portal-pen
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project-portal
  namespace: argocd
spec:
  description: Project for team Portal
  sourceRepos:
    - '*'
  destinations:
    - namespace: product-portal
      server: https://kubernetes.default.svc
    - namespace: product-portal-pen
      server: https://kubernetes.default.svc
    - namespace: product-iam
      server: https://kubernetes.default.svc
    - namespace: product-iam-pen
      server: https://kubernetes.default.svc
  # Allow all namespaced-scoped resources to be created, except for ResourceQuota, LimitRange, NetworkPolicy
  namespaceResourceBlacklist:
    - group: ''
      kind: ResourceQuota
    - group: ''
      kind: LimitRange
    - group: ''
      kind: NetworkPolicy
  roles:
    # A role which provides access to all applications in the project
    - name: team-admin
      description: All access to applications inside project-portal. Read only on project itself
      policies:
        - p, proj:project-portal:team-admin, applications, *, project-portal/*, allow
      groups:
        - catenax-ng:product-portal
