apiVersion: v1
kind: Namespace
metadata:
  name: product-semantics
---
apiVersion: v1
kind: Namespace
metadata:
  name: product-semantics-pen
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project-semantics
  namespace: argocd
spec:
  description: Project for team Semantics
  sourceRepos:
    - '*'
  destinations:
    - namespace: product-semantics
      server: https://kubernetes.default.svc
    - namespace: product-semantics-pen
      server: https://kubernetes.default.svc
  # Allow all namespaced-scoped resources to be created, except for ResourceQuota, LimitRange, NetworkPolicy
  namespaceResourceBlacklist:
    - group: ''
      kind: ResourceQuota
    - group: ''
      kind: LimitRange
    - group: ''
      kind: NetworkPolicy
  roles:
    # A role which provides access to all applications in the project
    - name: team-admin
      description: All access to applications inside project-portal. Read only on project itself
      policies:
        - p, proj:project-semantics:team-admin, applications, *, project-semantics/*, allow
      groups:
        - catenax-ng:product-semantics
