apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - applicationsets/app-dashboard-applicationset.yaml
  - applicationsets/argo-applicationset.yaml
  - applicationsets/ingress-applicationset.yaml
  - applicationsets/ingress-multisource-applicationset.yaml
  - applicationsets/certmanager-applicationset.yaml
  - applicationsets/tls-applicationset.yaml
  - applicationsets/reflector-applicationset.yaml
  - applicationsets/kube-prometheus-stack-applicationset.yaml
  - applicationsets/maintenance-dashboard-app-applicationset.yaml
  - applicationsets/kubeapps-applicationset.yaml
  - applicationsets/kyverno-multisource-applicationset.yaml
  - applicationsets/landing-page-applicationset.yaml
  - applicationsets/loki-applicationset.yaml
  - applications/vault-application.yaml
  - applications/gh-org-checks-application.yaml
  - applications/tractusx-gh-org-checks-application.yaml
  - cluster-secrets/hotel-budapest-secret.yaml
  - cluster-secrets/dev-cluster-secret.yaml
  - cluster-secrets/devsecops-testing-cluster-secret.yaml
  - cluster-secrets/stable-cluster-secret.yaml

# TODO 08.04.2022 CARSLEN: after vault cluster secret is available in vault, enable it here for deployment
#  - cluster-secrets/vault-cluster-secret.yaml
#  - cluster-secrets/example-cluster-secret.yaml
