apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - applicationsets/argo-applicationset.yaml
  - cluster-secrets/example-cluster-secret.yaml

patchesStrategicMerge:
  - configmap/argo-url.yaml
