apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - applicationsets/*.yaml
  - cluster-secrets/*.yaml

patchesStrategicMerge:
  - configmap/argo-url.yaml