apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - applicationsets/argo-applicationset.yaml
  - applicationsets/ingress-applicationset.yaml
  - applicationsets/certmanager-applicationset.yaml
  - applicationsets/tls-applicationset.yaml
  - applicationsets/reflector-applicationset.yaml
  - cluster-secrets/hotel-budapest-secret.yaml
  - cluster-secrets/dev-cluster-secret.yaml
# TODO 08.04.2022 CARSLEN: after vault cluster secret is available in vault, enable it here for deployment
#  - cluster-secrets/vault-cluster-secret.yaml
#  - cluster-secrets/example-cluster-secret.yaml
