apiVersion: v1
kind: Secret
metadata:
  annotations:
    avp.kubernetes.io/path: "devsecops/data/azure/demo.catena-x.net/azuredns-config"
  name: azuredns-config
  namespace: cert-manager
type: Opaque
stringData:
  VAULT_ADDR: https://vault.vault.demo.catena-x.net/
  AVP_TYPE: vault
  AVP_AUTH_TYPE: approle
  client-secret: <client-secret>
