apiVersion: v1
kind: Secret
metadata:
  annotations:
    avp.kubernetes.io/path: "devsecops/data/azure/demo.catena-x.net/azuredns-config"
  name: azuredns-config
  namespace: {{ .Release.Namespace}}
type: Opaque
stringData:
  client-secret: <client-secret>
