apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ingress-multisource-applicationset
spec:
  generators:
    - list:
        elements:
          - cluster: core
            cluster-name: in-cluster
            chartVersion: 4.10.0
            targetRevision: HEAD
            path: 'apps/ingress-nginx'
          - cluster: dev
            cluster-name: dev
            chartVersion: 4.10.0
            targetRevision: HEAD
            path: 'apps/ingress-nginx'
          - cluster: devsecops-testing
            cluster-name: devsecops-testing
            chartVersion: 4.10.0
            targetRevision: HEAD
            path: 'apps/ingress-nginx'
          - cluster: int
            cluster-name: hotel-budapest
            chartVersion: 4.10.0
            targetRevision: HEAD
            path: 'apps/ingress-nginx'
          - cluster: stable
            cluster-name: stable
            chartVersion: 4.10.0
            targetRevision: HEAD
            path: 'apps/ingress-nginx'
          - cluster: vault
            cluster-name: vault-cluster
            chartVersion: 4.10.0
            targetRevision: HEAD
            path: 'apps/ingress-nginx'
  template:
    metadata:
      name: '{{cluster}}-ingress-nginx'
      labels:
        app: 'ingress-nginx'
    spec:
      project: default
      sources:
        - repoURL: 'https://kubernetes.github.io/ingress-nginx'
          chart: ingress-nginx
          targetRevision: '{{chartVersion}}'
          helm:
            valueFiles:
              - $values/{{path}}/values.yaml
              - $values/{{path}}/values-{{cluster}}.yaml
        - repoURL: 'https://github.com/catenax-ng/k8s-cluster-stack'
          targetRevision: '{{targetRevision}}'
          ref: values
      destination:
        name: '{{cluster-name}}'
        namespace: 'default'
        server: ''
#      syncPolicy:
#        automated: {}
