apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kube-prometheus-stack-applicationset
spec:
  generators:
  - list:
      elements:
      - cluster: core
        cluster-name: in-cluster
        targetRevision: feature/monitoring_core_int
      - cluster: dev
        cluster-name: dev
        targetRevision: HEAD
      - cluster: hotel-budapest
        cluster-name: hotel-budapest
        targetRevision: HEAD


  template:
    metadata:
      name: '{{ cluster }}-kube-prometheus-stack'
      labels:
        app: kube-prometheus-stack
    spec:
      project: default
      source:
        plugin:
          name: argocd-vault-plugin-kustomize-helm-args
          env:
            - name: helm_args
              value: '-f values.yaml -f values-{{ cluster }}.yaml'
        repoURL: https://github.com/catenax-ng/k8s-cluster-stack
        targetRevision: '{{ targetRevision }}'
        path: apps/kube-prometheus-stack
      destination:
        name: '{{ cluster-name }}'
        namespace: monitoring
        server: ''
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          # https://github.com/prometheus-community/helm-charts/issues/1500#issuecomment-968892923
          # sync of CRD must use replace, also we default to ApplyOutOfSyncOnly
          - ApplyOutOfSyncOnly=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
