apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kyverno-multisource-applicationset
spec:
  generators:
    - list:
        elements:
          - cluster: core
            cluster-name: in-cluster
            targetRevision: HEAD
            path: 'apps/kyverno'
          - cluster: dev
            cluster-name: dev
            targetRevision: HEAD
            path: 'apps/kyverno'
          - cluster: devsecops-testing
            cluster-name: devsecops-testing
            targetRevision: HEAD
            path: 'apps/kyverno'
          - cluster: int
            cluster-name: hotel-budapest
            targetRevision: HEAD
            path: 'apps/kyverno'
          - cluster: stable
            cluster-name: stable
            targetRevision: HEAD
            path: 'apps/kyverno'
  template:
    metadata:
      name: '{{cluster}}-kyverno'
      labels:
        app: 'kyverno'
    spec:
      project: default
      sources:
        - repoURL: 'https://kyverno.github.io/kyverno'
          chart: kyverno
          targetRevision: 3.0.7
          helm:
            valueFiles:
              - $values/{{path}}/kyverno/values.yaml
              - $values/{{path}}/kyverno/values-{{cluster}}.yaml
        - repoURL: 'https://kyverno.github.io/policy-reporter'
          chart: policy-reporter
          targetRevision: 2.21.1
          helm:
            valueFiles:
              - $values/{{path}}/policy-reporter/values.yaml
              - $values/{{path}}/policy-reporter/values-{{cluster}}.yaml
        - repoURL: 'https://github.com/catenax-ng/k8s-cluster-stack'
          targetRevision: '{{targetRevision}}'
          ref: values
      destination:
        name: '{{cluster-name}}'
        namespace: 'kyverno'
        server: ''

      # Sync policy
      syncPolicy:
        automated: {}
        syncOptions:
          - ServerSideApply=true # https://kyverno.io/docs/installation/#notes-for-argocd-users
          - CreateNamespace=true
