apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kyverno-applicationset
spec:
  generators:
    - list:
        elements:
#          - cluster: devsecops-testing
#            cluster-name: devsecops-testing
#            targetRevision: feat/kyverno-monitoring
          - cluster: dev
            cluster-name: dev
            targetRevision: HEAD
          - cluster: hotel-budapest
            cluster-name: hotel-budapest
            targetRevision: HEAD
          - cluster: pre-prod
            cluster-name: pre-prod
            targetRevision: HEAD
          - cluster: beta
            cluster-name: beta
            targetRevision: HEAD
          - cluster: stable
            cluster-name: stable
            targetRevision: HEAD
  template:
    metadata:
      name: '{{ cluster }}-kyverno'
      labels:
        app: kyverno
    spec:
      project: default
      source:
        repoURL: https://github.com/catenax-ng/k8s-cluster-stack
        targetRevision: '{{ targetRevision }}'
        path: apps/kyverno
      destination:
        name: '{{ cluster-name }}'
        namespace: kyverno
        server: ''

      # Sync policy
      syncPolicy:
        # automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
        syncOptions:
          # https://kyverno.io/docs/installation/#notes-for-argocd-users
          - ServerSideApply=true
          - CreateNamespace=true
