apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pre-prod-apps-wave-b
spec:
  destination:
    name: ''
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: pre-prod/argocd-apps-wave-b
    repoURL: 'https://github.com/catenax-ng/catena-x-release-deployment.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
