apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  configManagementPlugins: |
    - name: avp-general
      generate:
        command: ["sh", "-c"]
        args: ["argocd-vault-plugin generate -s ${AVP_SECRET} ./"]
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  configManagementPlugins: |
      - name: avp-kustomize
        generate:
          command: ["sh", "-c"]
          args: ["kustomize build . | argocd-vault-plugin generate - -s ${AVP_SECRET}"]
#      - name: avp-helm
#        generate:
#          command: ["bash", "-c"]
#          args: ['helm template "$ARGOCD_APP_NAME" -f <(echo "$HELM_VALUES") . | argocd-vault-plugin generate -']