apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  configManagementPlugins: |-
    - name: argocd-vault-plugin
      generate:
        command: ["sh", "-c"]
        args: ["argocd-vault-plugin generate -s vault-secret ./"]
    - name: argocd-vault-plugin-helm
      init:
        command: [sh, -c]
        args: ["helm dependency update -n $ARGOCD_APP_NAMESPACE"]
      generate:
        command: ["sh", "-c"]
        args: ["helm template $ARGOCD_APP_NAME -n $ARGOCD_APP_NAMESPACE . | argocd-vault-plugin generate - -s vault-secret"]
    - name: argocd-vault-plugin-helm-args
      init:
        command: [sh, -c]
        args: ["helm dependency update -n $ARGOCD_APP_NAMESPACE"]
      generate:
        command: ["sh", "-c"]
        args: ["helm template $ARGOCD_APP_NAME -n $ARGOCD_APP_NAMESPACE ${helm_args} . | argocd-vault-plugin generate - -s vault-secret"]
    - name: argocd-vault-plugin-kustomize
      generate:
        command: ["sh", "-c"]
        args: ["kustomize build . | argocd-vault-plugin generate - -s vault-secret"]
    - name: argocd-vault-plugin-kustomize-helm-args
      init:
          command: [sh, -c]
          args: ["helm dependency update -n $ARGOCD_APP_NAMESPACE"]
      generate:
        command: ["sh", "-c"]
        args: ["helm template $ARGOCD_APP_NAME -n $ARGOCD_APP_NAMESPACE ${helm_args} . > manifest.yaml && kustomize build | argocd-vault-plugin generate - -s vault-secret"]
