apiVersion: v1
kind: Secret
metadata:
  name: idses-frontend-apps-repo
  namespace: argocd
  annotations:
    avp.kubernetes.io/path: "essential-services/data/deploy-key"
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: git@github.com:catenax-ng/product-idses-frontend-apps
  name: product-idses-frontend-apps-repo
  project: project-essential-services
  sshPrivateKey: |
    <idses-frontend-apps-deploy-key>
