apiVersion: v1
kind: Namespace
metadata:
  name: product-r-strategy-assistant
---
apiVersion: v1
kind: Namespace
metadata:
  name: product-r-strategy-assistant-pen
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project-r-strategy-assistant
  namespace: argocd
spec:
  description: Project for team Value Added Service
  sourceRepos:
    - '*'
  destinations:
    - namespace: product-r-strategy-assistant
      server: https://kubernetes.default.svc
    - namespace: product-r-strategy-assistant-pen
      server: https://kubernetes.default.svc
  # Allow all namespaced-scoped resources to be created, except for ResourceQuota, LimitRange, NetworkPolicy
  namespaceResourceBlacklist:
    - group: ''
      kind: ResourceQuota
    - group: ''
      kind: LimitRange
    - group: ''
      kind: NetworkPolicy
  roles:
    - name: team-admin
      description: All access to applications inside project-r-strategy-assistant. Read only on project itself
      policies:
        - p, proj:project-r-strategy-assistant:team-admin, applications, *, project-r-strategy-assistant/*, allow
        - p, proj:project-r-strategy-assistant:team-admin, exec, create, project-r-strategy-assistant/*, allow
      groups:
        - catenax-ng:product-r-strategy-assistant
