apiVersion: v1
kind: Secret
metadata:
  name: product-esc-backbone-blockexplorer
  namespace: argocd
  annotations:
    avp.kubernetes.io/path: "esc-backbone/data/deploy-key"
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: git@github.com:catenax-ng/product-esc-backbone-blockexplorer
  name: product-esc-backbone-blockexplorer-repo
  project: project-esc-backbone
  sshPrivateKey: |
    <product-esc-backbone-deploy-key>
