apiVersion: v1
kind: Secret
metadata:
  annotations:
    avp.kubernetes.io/path: "devsecops/data/clusters/example-cluster2"
  name: example-cluster-secret2
  labels:
    argocd.argoproj.io/secret-type: cluster
  namespace: argocd
type: Opaque
stringData:
  name: <name>
  server: <server>
  config: |
    {
      "bearerToken": <bearerToken>,
      "tlsClientConfig": {
        "insecure": false,
        "caData": <caData>
      }
    }