apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: default-applicationset
spec:
  generators:
  - list:
      elements:
      - cluster: core
        url: https://kubernetes.default.svc

  template:
    metadata:
      name: {{ cluster }}-ingress-nginx
      namespace: argocd
      labels:
        app: ingress-nginx
    spec:
      project: default
      source:
        helm:
          valueFiles:
            - values.yaml
        repoURL: https://github.com/catenax-ng/k8s-cluster-stack
        targetRevision: feature/A10DT-419-setup-default-apps
        path: apps/ingress/ingress-nginx

      destination:
        server: {{ url }}
        namespace: default
