apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

namespace: vault
resources:
- unsealer.yaml

commonLabels:
  provided-by: dt-devops-team