config:
  webhookAnnotations:
    "admissions.enforcer/disabled": 'true'
admissionController:
  replicas: 3
  serviceMonitor:
    enabled: true
backgroundController:
  replicas: 2
cleanupController:
  replicas: 2
reportsController:
  replicas: 2
  resources:
    limits:
      memory: 256Mi
grafana:
  enabled: true
