project: vault

destination:
  server: https://cxvaultakssrv-122a5b8a.hcp.germanywestcentral.azmk8s.io:443

certManager:
  name: vault-cert-manager
  destination:
    namespace: cert-manager
  source:
    repourl: https://charts.jetstack.io
    targetrevision: 1.7.2
  customvalues:
    installCRDs: true

ingressNginx:
  name: vault-ingress-nginx
  destination:
    namespace: default
  source:
    repourl: https://kubernetes.github.io/ingress-nginx
    targetrevision: 4.0.6
  customvalues:
    controller:
      ingressClassResource:
        default: true
      watchIngressWithoutClass: true
      config:
        # @url: https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#enable-underscores-in-headers
        enable-underscores-in-headers: "true"
      #extraArgs:
        #default-ssl-certificate: "default/www-tls"  # K8_NAMESPACE/K8_SECRET_NAME @url: https://kubernetes.github.io/ingress-nginx/user-guide/tls/#default-ssl-certificate    
    defaultBackend:
      enabled: true

ingress:
  name: vault-ingress
  destination:
    namespace: vault
  source:
    repourl: https://github.com/catenax-ng/vault.git
    targetrevision: vault
    path: vault/ingress

vault:
  name: vault
  destination:
    namespace: vault
  source:
    repourl: https://helm.releases.hashicorp.com
    targetrevision: 0.19.0
  seal:
    tenantid: passfromsecret
    clientid: passfromsecret
    clientsecret: passfromsecret
    azurevaultname: passfromsecret
    azurevaultkeyname: passfromsecret
    subscriptionid: passfromsecret

unseal:
  name: vault-unseal
  destination:
    namespace: vault
  source:
    repourl: https://github.com/catenax-ng/vault.git
    targetrevision: main
    path: vault/unseal
