apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
  avp.kubernetes.io/path: "clusters/dev/irs/argocd-notifications-secret"
stringData:
  channel-teams-url: <channel-teams-url>
