apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - manifest.yaml

patches:
  - patch: |-
      - op: add
        path: /metadata/labels/maintenance~1scan
        value: "true"
    target:
      version: v1
      kind: Service
      name: .*-kyverno-svc
