apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kyverno

resources:
  - manifest.yaml


# Here's the warning fix for sharedResourceWarning
patches:
  - target:
      kind: CustomResourceDefinition
    patch: |-
      - op: remove
        path: /metadata/labels/app.kubernetes.io~1instance
