apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
  - namespace.yaml

helmCharts:
  - name: kyverno
    repo: https://kyverno.github.io/kyverno/
    version: 2.6.0
    releaseName: kyverno
    namespace: kyverno

# Here's the warning fix for sharedResourceWarning
patches:
  - target:
      kind: CustomResourceDefinition
    patch: |-
      - op: remove
        path: /metadata/labels/app.kubernetes.io~1instance
