config:
  webhookAnnotations:
    "admissions.enforcer/disabled": 'true'
admissionController:
  replicas: 3
  serviceMonitor:
    enabled: false
backgroundController:
  replicas: 2
  serviceMonitor:
    enabled: false
cleanupController:
  replicas: 2
  serviceMonitor:
    enabled: false
reportsController:
  replicas: 2
  serviceMonitor:
    enabled: false
grafana:
  enabled: true
  namespace: monitoring
  configMapName: kyverno-dashboards
