{
 "title": "Portal",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Errors",
   "type": "timeseries",
   "description": "Count of errors for each given container",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(container) (count_over_time({container=~\"administration-service|marketplace-app-service|processes-worker|notification-service|registration-service|services-service\"} |= `Level` | json log | __error__=`` | line_format `{{.log}}` | json | __error__=`` | unpack  | Level = `Error` [$__interval]))"
    }
   ]
  },
  {
   "title": "Error Count by StatusCode",
   "type": "timeseries",
   "description": "Count of errors for each given container",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(Properties_StatusCode, container) (count_over_time({container=~\"administration-service|marketplace-app-service|processes-worker|notification-service|registration-service|services-service\"} |= `Level` | json log | __error__=`` | line_format `{{.log}}` | json | __error__=`` | unpack | Level = `Error` [$__interval]))"
    }
   ]
  },
  {
   "title": "Warnings",
   "type": "timeseries",
   "description": "Count of warnings for each given container",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(container) (count_over_time({container=~\"administration-service|marketplace-app-service|processes-worker|notification-service|registration-service|services-service\"} |= `Level` | json log | __error__=`` | line_format `{{.log}}` | json | __error__=`` | unpack  | Level = `Warning` [$__interval]))"
    }
   ]
  },
  {
   "title": "Elapsed time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by(Properties_Elapsed) (avg_over_time({container=~\"administration-service|marketplace-app-service|processes-worker|notification-service|registration-service|services-service\"} |= `Elapsed` | json log | __error__=`` | line_format `{{.log}}` | json | __error__=`` | unwrap Properties_Elapsed | __error__=`` [$__interval]) by (container))"
    }
   ]
  }
 ]
}