{
 "title": "Product Portal",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "app",
    "label": "App",
    "query": "administration-service,marketplace-app-service,processes-worker,notification-service,registration-service,services-service"
   },
   {
    "name": "level",
    "label": "Log Level",
    "query": "Information, Verbose, Debug, Error, Warning, Critial"
   },
   { "name": "search", "label": "Search Query" }
  ]
 },
 "panels": [
  {
   "title": "Errors",
   "type": "timeseries",
   "description": "Count of errors for each given container",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(app) (count_over_time({app=~\"administration-service|marketplace-app-service|processes-worker|notification-service|registration-service|services-service\"} |= `Level` | json | __error__=`` | unpack | Properties_StatusCode >= 400 [$__interval]))"
    }
   ]
  },
  {
   "title": "Error Count by StatusCode",
   "type": "timeseries",
   "description": "Count of errors for each given container",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(Properties_StatusCode, app) (count_over_time({app=~\"administration-service|marketplace-app-service|notification-service|registration-service|services-service\"} |= `Level` | json | __error__=`` | unpack | Properties_StatusCode >= 400 [$__interval]))"
    }
   ]
  },
  {
   "title": "Warnings",
   "type": "timeseries",
   "description": "Count of warnings for each given container",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(app) (count_over_time({app=~\"administration-service|marketplace-app-service|processes-worker|notification-service|registration-service|services-service\"} |= `Level` | json | __error__=`` | unpack  | Level = `Warning` [$__interval]))"
    }
   ]
  },
  {
   "title": "Elapsed time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by(Properties_Elapsed) (avg_over_time({app=~\"administration-service|marketplace-app-service|processes-worker|notification-service|registration-service|services-service\"} |= `Elapsed` | json | __error__=`` | unwrap Properties_Elapsed | __error__=`` [$__interval]) by (app))"
    }
   ]
  },
  {
   "title": "Combined Logs",
   "type": "logs",
   "gridPos": { "h": 24, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{namespace=\"product-iam\", app=~\"$app\"} |= `Level` | json | __error__=`` | unpack | Level = \"$level\" | line_format `{{.RenderedMessage}}` |~ `(?i)$search`"
    }
   ]
  }
 ]
}