apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana-ingress
  namespace: {{ .Release.Namespace}}
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: grafana.{{ .Values.domain}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.cluster}}-kube-prometheus-stack-grafana
                port:
                  number: 80
  tls:
    - hosts:
        - grafana.{{ .Values.domain}}
      secretName: tls-secret


