domain: "demo.catena-x.net"
vault:
  server:
    ha:
      config: |
        ui = true
        listener "tcp" {
          tls_disable = 1
          address = "[::]:8200"
          cluster_address = "[::]:8201"
        }
        storage "raft" {
          path = "/vault/data"
        }
        service_registration "kubernetes" {}
        disable_mlock = true
      enabled: true
      raft:
        enabled: true
        config: |
          ui = true
          listener "tcp" {
            tls_disable = 1
            address = "[::]:8200"
            cluster_address = "[::]:8201"
          }
          storage "raft" {
            path = "/vault/data"
          }
          service_registration "kubernetes" {}
          disable_mlock = true
    extraEnvironmentVars:
      VAULT_SEAL_TYPE: "azurekeyvault"
      VAULT_AZUREKEYVAULT_VAULT_NAME: "cx-vault-unseal"
      VAULT_AZUREKEYVAULT_KEY_NAME: "hashicorp-vault-key"
      AZURE_TENANT_ID: "495463c3-0991-4659-9cc5-94b4a3f7b1d6"
      AZURE_CLIENT_ID: "eed491d9-d302-4f3a-93aa-973e3d3fe442"
    extraSecretEnvironmentVars:
      - envName: AZURE_CLIENT_SECRET
        secretName: azure-vault-secret
        secretKey: client-secret

dex:
  config:
    # Set it to a valid URL
    issuer: http://dex.vault.demo.catena-x.net

    # See https://dexidp.io/docs/storage/ for more options
    storage:
      type: memory

    # Enable at least one connector
    # See https://dexidp.io/docs/connectors/ for more options
    enablePasswordDB: true
    connectors:
    - type: github
      id: github
      name: GitHub
      config:
        clientID: '<path:/devsecops/data/clusters/core/github-oauth#oAuthClientId>'
        clientSecret: '<path:/devsecops/data/clusters/core/github-oauth#oAuthClientSecret>'
        orgs:
        - name: catenax-ng
    url: "https://dex.vault.demo.catena-x.net"    
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
    - host: dex.vault.demo.catena-x.net
      paths:
        - path: /
          pathType: Prefix
    tls:
    - hosts:
        - dex.vault.demo.catena-x.net
      secretName: tls-secret