apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: vault
    meta.helm.sh/release-namespace: argocd
spec:
  project: vault
  source:
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 0.19.0
    helm:
      parameters:
        - name: server.ha.enabled
          value: 'true'
        - name: server.ha.raft.enabled
          value: 'true'
        - name: server.ha.raft.config
          value: |
            ui = true
            listener "tcp" {
              tls_disable = 1
              address = "[::]:8200"
              cluster_address = "[::]:8201"
            }
            storage "raft" {
              path = "/vault/data"
            }
            service_registration "kubernetes" {}
            disable_mlock = true
            seal "azurekeyvault" {
              tenant_id = "${AZURE_TENANT_ID}"
              client_id = "${AZURE_CLIENT_ID}"
              client_secret = "${AZURE_CLIENT_SECRET}"
              vault_name = "${AZURE_VAULT_NAME}"
              key_name = "${AZURE_VAULT_KEY_NAME}"
              subscription_id = "${AZURE_SUBSCRIPTION_ID}"
            }
        - name: server.ha.config
          value: |
            ui = true
            listener "tcp" {
              tls_disable = 1
              address = "[::]:8200"
              cluster_address = "[::]:8201"
            }
            storage "raft" {
              path = "/vault/data"
            }
            service_registration "kubernetes" {}
            disable_mlock = true
            seal "azurekeyvault" {
              tenant_id = "${AZURE_TENANT_ID}"
              client_id = "${AZURE_CLIENT_ID}"
              client_secret = "${AZURE_CLIENT_SECRET}"
              vault_name = "${AZURE_VAULT_NAME}"
              key_name = "${AZURE_VAULT_KEY_NAME}"
              subscription_id = "${AZURE_SUBSCRIPTION_ID}"
            }
    chart: vault
  destination:
    server: "https://cxvaultakssrv-122a5b8a.hcp.germanywestcentral.azmk8s.io:443"
    namespace: "vault"
