apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  annotations:
    avp.kubernetes.io/path: "devsecops/data/clusters/devsecops-testing/github-oauth"
data:
  exec.enabled: "true"
  dex.config: |
    connectors:
      - type: github
        id: github
        name: GitHub
        config:
          clientID: '<oAuthClientId>'
          clientSecret: '<oAuthClientSecret>'
          orgs:
          - name: catenax-ng
  url: "https://argo.devsecops-testing.demo.catena-x.net"
