apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: environment-core
  namespace: argocd
  labels:
    environment: core
spec:
  project: default
  source:
    repoURL: https://github.com/catenax-ng/k8s-cluster-stack
    targetRevision: feature/A1ODT-409_Secret_handling_with_Vault/A1ODT-423
    path: environments/core
    plugin:
      name: argocd-vault-plugin-kustomize
      env:
        - name: AVP_SECRET
          value: devsecops-team-vault-secret

  destination:
    name: in-cluster
    namespace: argocd
    server: ''

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
