apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devsecops-testing-config
  namespace: argocd
  labels:
    environment: devsecops-testing
spec:
  project: default
  source:
    repoURL: https://github.com/catenax-ng/product-onboarding
    targetRevision: HEAD
    path: cluster/devsecops-testing
    plugin:
      name: argocd-vault-plugin-kustomize

  destination:
    name: devsecops-testing
    namespace: argocd
