apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: environment-hotel-budapest
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/catenax-ng/k8s-cluster-stack
    targetRevision: HEAD
    path: environment/hotel-budapest

  destination:
    name: hotel-budapest
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
