apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hotel-budapest-config
  namespace: argocd
  labels:
    environment: hotel-budapest
spec:
  project: default
  source:
    repoURL: https://github.com/catenax-ng/k8s-cluster-stack
    targetRevision: HEAD
    path: environments/hotel-budapest
    plugin:
      name: argocd-vault-plugin-kustomize

  destination:
    name: hotel-budapest
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
