landing-page:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    hosts:
      - host: home.pre-prod.demo.catena-x.net
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: tls-secret
        hosts:
          - home.pre-prod.demo.catena-x.net
  service:
    environment: "PRE-PROD"
